### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by kakins** [azixMcAze/SerializableDictionary#12]
![image](https://user-images.githubusercontent.com/14915247/72399627-5d240b80-370c-11ea-9e9d-224cd26256d3.png)

This is what my editor looks like when I add a serialized dictionary field.  It's a simple Dictionary<string, string>, as in your examples.  It looks like it is displaying the List<T> for keys and values, and wants me to set the size.  Doing so throws an error.

**Comment by azixMcAze** [comment]
Hello @kakins, did you create a `SerializableDictionaryPropertyDrawer` for your dictionnary ?
If you are using the version on the asset store, you use instead [the version on GitHub](https://github.com/azixMcAze/Unity-SerializableDictionary/releases/tag/v1.2.0) that doesn't need to setup a `SerializableDictionaryPropertyDrawer`.

**Comment by kakins** [comment]
Ok I may give that a shot, thank you.  I ended up just serializing a list<string, myobject> instead, which seems to work for now.
