### ISSUE TITLE
[Feature Request] SerializableHashSet

### ISSUE THREAD

**Issue by Hurri04** [azixMcAze/SerializableDictionary#7]
Hey there, 

I've been using your implementation of the SerializableDictionary in a few projects now since it provides a really nice UI in the inspector.

Something I've been looking for for a while now is a SerializableHashSet though. Sometimes there are no values which could be added to a collection of keys to justify using a Dictionary when a HashSet would be enough.

While it's easy to implement one myself e.g. like below, it does not have the nice inspector features your plugin provides:

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[Serializable]
public class SerializableHashSet<T> : HashSet<T>, ISerializationCallbackReceiver
{
	[NonSerialized]
	public HashSet<T> Keys = new HashSet<T>();
	[SerializeField]
	private List<T> serializedKeys = new List<T>();

	public void OnBeforeSerialize()
	{
		serializedKeys.Clear();
		foreach(T key in Keys)
		{
			serializedKeys.Add(key);
		}
	}

	public void OnAfterDeserialize()
	{
		Keys.Clear();
		foreach(T key in serializedKeys)
		{
			Keys.Add(key);
		}
	}
}

In case you are still maintaining this project, could you imagine adding support for SerializableHashSets with a PropertyDrawer? I'm sure other people out there could use this as well ;)

**Comment by azixMcAze** [comment]
Hi !
This projet is not abandonned :)
This is a good idea and I will try to modify the current inspector to handle hashsets too

**Comment by azixMcAze** [comment]
Hi, I have added support for a SeriaizableHashSet in the master branch
Can you test it ?
It is only available when using the .Net 4.6 runtime version (due to ISet<> not existing in .Net 3.5)

**Comment by Hurri04** [comment]
Hey!

Much appreciated!
I tested it with enum, int and string for now and it seems to work well: https://i.imgur.com/sKEOdGW.png
Tested with:
* Unity 2018.3.0f2
* Scripting Runtime Version = ".NET 4.x Equivalent"
* Scripting Backend = "IL2CPP"
* Api Compatibility Level = ".NET Standard 2.0"

What confused me a little at the beginning was that the derived PropertyDrawers have to derive from "SerializableDictionaryPropertyDrawer" instead of there being a "SerializableHashSetPropertyDrawer" class. I guess this is to avoid duplicate code?
Would it be possible/ make sense to have these 2 classes derive from a base class which holds the methods instead?

Other than that, looks good to me.
If there's anything else you'd like to have tested just ask :)

**Comment by azixMcAze** [comment]
Hi, Since version 1.2.0, you no longer have to create a derivated class from `SerializableDictionaryPropertyDrawer`! You just have to create a derivated class from `SerializableHashSet<T>`.
`SerializableDictionaryPropertyDrawer` now supports both `SerializableDictionary` and `SerializableHashSet`. 

The trick used to remove the need for derived `SerializableDictionaryPropertyDrawer` cannot be use for `SerializableHashSet`s on .Net 3.5, unfortunately.

**Comment by Hurri04** [comment]
Oh, that's neat. It seems I've still been using 1.1.0 in my other projects since that's the current version on the Unity Asset Store.

**Comment by Hurri04** [comment]
I just noticed that this issue was left open so I'm closing it now since the new feature works nicely 👍
